# Generated by Django 3.2.18 on 2023-05-18 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0002_auto_20230518_1541'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('nationality', models.CharField(choices=[('KOR', 'South Korea'), ('USA', 'United States'), ('JPN', 'Japan'), ('CHN', 'China')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(blank=True, max_length=100)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('charge', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('venue', models.TextField(blank=True, max_length=100)),
                ('thumbnail', models.ImageField(blank=True, upload_to=posts.models.Exhibition.img_path)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='apis.item')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('closed_days', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to=posts.models.Theme.img_path)),
                ('exhibitions', models.ManyToManyField(related_name='themes', to='posts.Exhibition')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('exhibition', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='posts.exhibition')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
