# Generated by Django 3.2.18 on 2023-05-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='venue',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='thumbnail',
        ),
    ]
