# Generated by Django 3.2.18 on 2023-05-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230513_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='address',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='begin',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='end',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='gallery',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='charge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='grade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='peroid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.artist'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('exhibitions', models.ManyToManyField(related_name='themes', to='posts.Exhibition')),
            ],
        ),
    ]
