# Generated by Django 3.2.18 on 2023-05-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230518_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='description',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='charge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='grade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='venue',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
