# Generated by Django 3.2.18 on 2023-05-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230515_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='image_url',
            new_name='referenceIdentifier',
        ),
    ]
