# Generated by Django 3.2.18 on 2023-05-15 15:18

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0001_initial'),
        ('posts', '0003_rename_image_url_exhibition_referenceidentifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
