# Generated by Django 3.2.18 on 2023-05-16 00:25

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('posts', '0003_rename_image_url_exhibition_referenceidentifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/', verbose_name='대표이미지'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='referenceIdentifier',
            field=models.URLField(default='#'),
        ),
    ]
