# Generated by Django 3.2.18 on 2023-05-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230518_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
