# Generated by Django 3.2.18 on 2023-05-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230514_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='uci',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
