# Generated by Django 3.2.18 on 2023-05-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_exhibition_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
    ]
