# Generated by Django 3.2.18 on 2023-05-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_exhibition_uci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='peroid',
            new_name='period',
        ),
    ]
