# Generated by Django 3.2.18 on 2023-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_peroid_exhibition_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
