# Generated by Django 3.2.18 on 2023-05-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_thumbnails_theme_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='artists',
            field=models.ManyToManyField(related_name='exhibitions', to='posts.Artist'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='posts.gallery'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
