# Generated by Django 3.2.18 on 2023-05-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230518_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='gallery',
            name='contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='closed_days',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
