# Generated by Django 3.2.18 on 2023-05-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230518_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='nationality',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
