# Generated by Django 3.2.18 on 2023-05-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230518_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='address',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='venue',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='closed_days',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
