# Generated by Django 3.2.18 on 2023-05-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20230518_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='exhibitions', to='posts.Artist'),
        ),
    ]
