# Generated by Django 3.2.18 on 2023-05-17 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_exhibitions',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='posts.Exhibition'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_reviews',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='posts.Review'),
        ),
        migrations.AlterField(
            model_name='user',
            name='visited_exhibitions',
            field=models.ManyToManyField(blank=True, related_name='visited_users', to='posts.Exhibition'),
        ),
    ]
