# Generated by Django 3.2.18 on 2023-05-18 05:26

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('server', models.TextField()),
                ('path', models.TextField()),
                ('param_keys', models.TextField()),
                ('field_keys', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.IntegerField()),
                ('thumbnail', models.ImageField(blank=True, upload_to=apis.models.Item.img_path)),
                ('title', models.TextField(blank=True)),
                ('alternativeTitle', models.TextField(blank=True)),
                ('creator', models.TextField(blank=True)),
                ('regDate', models.TextField(blank=True)),
                ('collectionDb', models.TextField(blank=True)),
                ('subjectCategory', models.TextField(blank=True)),
                ('subjectKeyword', models.TextField(blank=True)),
                ('extent', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('spatial', models.TextField(blank=True)),
                ('temporalCoverage', models.TextField(blank=True)),
                ('person', models.TextField(blank=True)),
                ('language', models.TextField(blank=True)),
                ('sourceTitle', models.TextField(blank=True)),
                ('referenceIdentifier', models.TextField(blank=True)),
                ('rights', models.TextField(blank=True)),
                ('copyrightOthers', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('contributor', models.TextField(blank=True)),
                ('eventPeriod', models.TextField(blank=True)),
                ('charge', models.TextField(blank=True)),
                ('grade', models.TextField(blank=True)),
                ('venue', models.TextField(blank=True)),
            ],
        ),
    ]
