# Generated by Django 3.2.18 on 2023-05-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_apiresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiResponse',
        ),
    ]
